let p=document.createElement("p");
p.innerHTML="Hi ! i am shubham";
let body=document.querySelector("body");
body.append(p);
p.style.color="red";
let h3=document.createElement("h3");
h3.innerHTML="I am blue H1";
p.insertAdjacentElement("afterend",h3);
h3.style.color="blue";
let div1=document.createElement("div");
let h1=document.createElement("h1");
let p1=document.createElement("p");
h1.innerText="I am in div";
p1.innerText="ME TOO!";
div1.append(h1);
div1.append(p1);
div1.style.border="2px solid black";
div1.style.backgroundColor="pink";
div1.classList.add("box");
body.append(div1);